version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            npm install --quiet
      - run: 
          name: test
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
      - run:
          name: Run ESLint
          command:
            echo "hello"
            #npm run lint
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Install node
          command: |
            set +e             
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v8
            nvm alias default v8
            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Run test for hello-engine
          command: |
            cd hello-engine
            ./test-hello-engine.sh
      - run:
          name: Kill the engine between tests
          command: docker rm -f `docker container ps -qa` # Kills all containers that are running
      - run:
          name: Run test for hello-data
          command: |
            cd hello-data
            ./test-hello-data.sh
      - run:
          name: Run test for hello-visualization
          background: true
          command: |
            cd hello-visualization
            npm install
            ./node_modules/.bin/webdriver-manager update
            docker rm -f `docker container ps -qa`
            docker-compose up -d
            npm run start
      - run:
          name: Run test for hello-visualization2
          command: |
            sleep 35
            cd hello-visualization
            npm run test
